/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import hci_project.ExamInfo;
import hci_project.Question;
import hci_project.management;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.swing.JFileChooser;
import javax.swing.border.TitledBorder;
import org.xml.sax.SAXException;

/**
 *
 * @author moroclash
 */

public class GnerateFrame extends javax.swing.JPanel {

    /**
     * Creates new form GnerateFrame
     */
    private String subject;
    private int subjectNum,CH,CM,CE;
    public GnerateFrame(String Subjectname) {
        initComponents();
        this.subject = Subjectname;
        TitledBorder titel =new TitledBorder("Exam Generrator");
        titel.setTitleFont(new Font("Chiller", Font.BOLD, 28));
        jLabel2.setText(subject);
        try {
            this.subjectNum = management.QuestionsNumber(subject, "data/Data.xml");
            jLabel11.setText(Integer.toString(this.subjectNum));
        } catch (Exception ex) {
            System.out.println("Error in line 36 in constractor of GeneratFrame *~*");
        } 
        ErrorMassage.setText("");
        CH = 0;CM = 0;CE = 0;
        Question Q;
        try{
            for(int k = 1 ; k<= subjectNum ; k++)
            {
            Q = management.search(subject, Integer.toString(k), "data/Data.xml");
            if(Q.getQlevel() == 1)
                  CE++;
            else if(Q.getQlevel() == 2)
                  CM++;
            else
                 CH++;

          }
          jLabel15.setText(Integer.toString(CE));
          jLabel16.setText(Integer.toString(CM));
          jLabel17.setText(Integer.toString(CH));
        }
        catch(Exception ex)
        {
            System.out.println("Error in constructor of GeneratorFrame *~*");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ErrorMassage = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();

        jLabel10.setText("jLabel10");

        setBackground(new java.awt.Color(210, 238, 198));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Exam Genrator", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Jomolhari", 1, 24))); // NOI18N
        setPreferredSize(new java.awt.Dimension(926, 600));

        jLabel1.setText("Subject :");

        jLabel2.setText("SubjectName");

        jLabel3.setText("Modle Numper :");

        jTextField1.setText("Numper");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Exam  Defculty :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Medium", "Hard" }));

        jTextField2.setText("Numper");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Question Numper :");

        jLabel6.setText("Location :");

        jButton1.setText("Chose");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField3.setText("Location");
        jTextField3.setEnabled(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Exam Name :");

        jTextField4.setText("Exam name");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel8.setText(".PDF");

        jButton2.setText("Generate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Question Numper :");

        jLabel11.setText("jLabel11");

        ErrorMassage.setText("ErrorMassage");

        jLabel12.setText("Easy question :");

        jLabel13.setText("Meduim question :");

        jLabel14.setText("Hard question :");

        jLabel15.setText("enable");

        jLabel16.setText("enable");

        jLabel17.setText("enaple");

        jLabel18.setText("Exam Time : ");

        jLabel19.setText("Exam Date :");

        jLabel20.setText("Exam Place : ");

        jTextField6.setText("Exam Place");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFormattedTextField1.setText("1/1/11");

        jLabel21.setText("Houre");

        jTextField5.setText("Time");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19)
                                .addComponent(jLabel18)))
                        .addGap(52, 52, 52)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                            .addComponent(jTextField1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel20)
                                .addGap(42, 42, 42)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(ErrorMassage, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(44, 44, 44)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGap(52, 52, 52)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(ErrorMassage, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser file = new JFileChooser();
        file.setSize(400, 300);
        file.setCurrentDirectory(new File("."));
        file.setDialogTitle("Chose Folder");
        file.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        file.setAcceptAllFileFilterUsed(false);
        if (file.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
          jTextField3.setText(file.getSelectedFile().getAbsolutePath());
        }    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try
        {
            int Qn = Integer.parseInt(jTextField2.getText());
            try{
                int Mn = Integer.parseInt(jTextField1.getText());
                if(jTextField2.getText().equals("")||jTextField1.getText().equals(""))
                {
                    ErrorMassage.setForeground(Color.red);
                    ErrorMassage.setText("Please Enter Number -_-");
                }
                else if(Integer.parseInt(jTextField2.getText())<3)
                {
                    ErrorMassage.setForeground(Color.red);
                    ErrorMassage.setText("Please Enter Question number more than 3 -_-");
                }
                else
                {
                    if(jTextField3.getText().equals("Location"))
                    {
                        ErrorMassage.setForeground(Color.red);
                        ErrorMassage.setText("Please Choose Location -_-");
                    }
                    else
                    {
                        if(jTextField4.getText().equals("File name")||jTextField4.getText().equals(""))
                        {
                            ErrorMassage.setForeground(Color.red);
                            ErrorMassage.setText("Please Enter File name -_-");
                            jTextField4.setText("");
                        }
                        else
                        {
                            boolean flage = false;
                            for(int i =0 ;i<jTextField4.getText().length();i++)
                            {
                                if(jTextField4.getText().charAt(i) != ' ')
                                {
                                    flage = true;
                                    break;
                                }
                            }
                            if(!flage)
                            {
                                ErrorMassage.setForeground(Color.red);
                                ErrorMassage.setText("Please Enter File name -_-");
                                jTextField4.setText("");
                            }
                            else 
                            {
                             try{
                                int time = Integer.parseInt(jTextField5.getText());
                                flage = false;
                                for(int i =0 ;i<jTextField5.getText().length();i++)
                                {
                                    if(jTextField5.getText().charAt(i) != ' ')
                                    {
                                        flage = true;
                                        break;
                                    }
                                }
                               if(jTextField5.getText().equals("")||!flage)
                               {
                                   ErrorMassage.setForeground(Color.red);
                                   ErrorMassage.setText("Please Enter Exam Time -_-");
                               }
                               else
                               {
                                   System.out.println(jFormattedTextField1.getText());/////
                                   if(jFormattedTextField1.getText().equals(""))
                                   {
                                        ErrorMassage.setForeground(Color.red);
                                        ErrorMassage.setText("Please Enter Exam Date -_-");
                                   }
                                   else
                                   {
                                        flage = false;
                                        for(int i =0 ;i<jTextField6.getText().length();i++)
                                        {
                                            if(jTextField6.getText().charAt(i) != ' ')
                                            {
                                                flage = true;
                                                break;
                                            }
                                        }
                                       if(jTextField6.getText().equals("")||!flage||jTextField6.getText().equals("Exam Place"))
                                       {
                                          ErrorMassage.setForeground(Color.red);
                                          ErrorMassage.setText("Please Enter place Exam -_-");
                                       }
                                       else
                                       {
                                           if(subjectNum < Qn)
                                           {
                                              ErrorMassage.setForeground(Color.red);
                                              ErrorMassage.setText("Sorry no enough Questions <_>"); 
                                           }
                                           else
                                           {
                                               boolean fla = false;
                                               int  E2  , E3 , E4;
                                               E2 =Qn/2;E3 =Qn/3 ;E4= Qn-(E2+E3);
                                               if(jComboBox1.getSelectedIndex() == 0)
                                               {
                                                   if(CE < E2)
                                                   {
                                                       ErrorMassage.setForeground(Color.red);
                                                       ErrorMassage.setText("Sorry no enough Easy Questions to Gnerat Exam <_>");
                                                   }
                                                   else if(CM < E3)
                                                   {
                                                       ErrorMassage.setForeground(Color.red);
                                                       ErrorMassage.setText("Sorry no enough Medium Questions to Gnerat Exam <_>");
                                                   }
                                                   else if (CH < E4)
                                                   {
                                                       ErrorMassage.setForeground(Color.red);
                                                       ErrorMassage.setText("Sorry no enough Medium Questions to Gnerat Exam <_>");
                                                   }
                                                   else
                                                   {
                                                       fla = true;
                                                   }
                                               }
                                               else if(jComboBox1.getSelectedIndex() == 1)
                                               {
                                                   if(CE < E3)
                                                   {
                                                       ErrorMassage.setForeground(Color.red);
                                                       ErrorMassage.setText("Sorry no enough Easy Questions to Gnerat Exam <_>");
                                                   }
                                                   else if(CM < E2)
                                                   {
                                                       ErrorMassage.setForeground(Color.red);
                                                       ErrorMassage.setText("Sorry no enough Medium Questions to Gnerat Exam <_>");
                                                   }
                                                   else if (CH < E4)
                                                   {
                                                       ErrorMassage.setForeground(Color.red);
                                                       ErrorMassage.setText("Sorry no enough Medium Questions to Gnerat Exam <_>");
                                                   }
                                                   else
                                                   {
                                                       fla = true;
                                                   }
                                               }
                                               else 
                                               {
                                                   if(CE < E4)
                                                   {
                                                       ErrorMassage.setForeground(Color.red);
                                                       ErrorMassage.setText("Sorry no enough Easy Questions to Gnerat Exam <_>");
                                                   }
                                                   else if(CM < E3)
                                                   {
                                                       ErrorMassage.setForeground(Color.red);
                                                       ErrorMassage.setText("Sorry no enough Medium Questions to Gnerat Exam <_>");
                                                   }
                                                   else if (CH < E2)
                                                   {
                                                       ErrorMassage.setForeground(Color.red);
                                                       ErrorMassage.setText("Sorry no enough Medium Questions to Gnerat Exam <_>");
                                                   }
                                                   else
                                                   {
                                                       fla = true;
                                                   }
                                               }
                                               
                                               try{
                                                    if(!management.ExmeQuestionNumper(subject, jTextField4.getText()).equals("0"))
                                                    {
                                                        ErrorMassage.setForeground(Color.red);
                                                        ErrorMassage.setText("Sorry the exam name is existe<_>");
                                                    }
                                               }
                                               catch(Exception ex)
                                               {
                                                   if(fla)
                                                    {
                                                   String ss = jTextField3.getText()+"/"+jTextField4.getText();
                                                   ExamInfo x = new ExamInfo();
                                                   x.setDate(jFormattedTextField1.getText());
                                                   x.setTime(jTextField5.getText());
                                                   x.setExamPlace(jTextField6.getText());
                                                   x.setExamname(subject);
                                                   x.setExamlvl(Integer.toString(jComboBox1.getSelectedIndex()+1));
                                                   x.setExammodel(jTextField1.getText());
                                                   management.Make3Array(Qn, Mn, jComboBox1.getSelectedIndex()+1,ss, subject,jTextField4.getText(),x,jTextField3.getText());
                                                   ErrorMassage.setForeground(Color.decode("#264b14"));
                                                   ErrorMassage.setText("Generat Exams Done! ^_^");
                                                   jTextField1.setText("Numper");
                                                   jTextField2.setText("Numper");
                                                   jTextField3.setText("Location");
                                                   jTextField4.setText("File Name");
                                                   jComboBox1.setSelectedIndex(0);
                                                    }
                                               }
                                           }
                                        }
                                   }
                               
                               }
                            }catch(Exception ex)
                            {
                              ErrorMassage.setForeground(Color.red);
                              ErrorMassage.setText("please ente exam time <_>");  
                            }
                               
                            }   
                          
                        }

                    }

                }
            }catch(Exception ex)
            {
                ErrorMassage.setForeground(Color.red);
                ErrorMassage.setText("Please Enter Model Number  -_-");
                jTextField1.setText("");
            }
        }
        catch(Exception ex)
        {
            ErrorMassage.setForeground(Color.red);
            ErrorMassage.setText("Please Enter Question Number  -_-");
            jTextField2.setText("");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrorMassage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
