/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import hci_project.ExamInfo;
import hci_project.management;
import java.awt.Color;
import java.awt.event.ItemListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author moroclash
 */
public class main_menu extends javax.swing.JPanel {

    /**
     * Creates new form main_menu
     */
    public main_menu(ArrayList<String> a) {
        initComponents();
        ErrorMassage.setText("");
        for(int i =0 ;i <a.size();i++)
        {
            jComboBox1.addItem(a.get(i));
            System.out.println((String)jComboBox1.getItemAt(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ErrorMassage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(186, 242, 172));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Main Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Mono", 1, 24))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 600));
        setLayout(null);

        jLabel1.setText("select Subject :");
        add(jLabel1);
        jLabel1.setBounds(40, 100, 140, 30);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1);
        jComboBox1.setBounds(170, 100, 360, 30);

        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(170, 150, 110, 30);

        jLabel2.setText("New Subject : ");
        add(jLabel2);
        jLabel2.setBounds(50, 300, 130, 30);

        jTextField1.setText("Enter Subject Name");
        jTextField1.setToolTipText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(160, 300, 360, 30);

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(550, 300, 110, 30);

        jButton3.setBackground(new java.awt.Color(173, 57, 57));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(300, 150, 100, 30);

        jButton4.setText("Generate Exam");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(410, 150, 190, 30);

        ErrorMassage.setFont(new java.awt.Font("Century Schoolbook L", 3, 24)); // NOI18N
        ErrorMassage.setText("Error massage");
        add(ErrorMassage);
        ErrorMassage.setBounds(180, 210, 470, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(jComboBox1.getSelectedItem()==null)
       {
           ErrorMassage.setForeground(Color.red);
           ErrorMassage.setText("please Add subject to can select ^_^");
       }
       else
       {
        try {
            int err = management.QuestionsNumber((String)jComboBox1.getSelectedItem(), "data/Data.xml");
            ArrayList<ExamInfo> a= management.SubjectExams((String)jComboBox1.getSelectedItem());
            ArrayList<String> s = new ArrayList<>();
            for(ExamInfo x : a)
            {
                s.add(x.getExamname());
                System.out.println(x.getExamname());
            }
            Search_frame search = new Search_frame((String)jComboBox1.getSelectedItem(),Integer.toString(err), s);
            search.setBounds(0, 0,1048, 660);
            this.setVisible(false);
            this.removeAll();
            this.add(search);
            this.repaint();
            this.setVisible(true);
            search.setVisible(true);
        } catch (SAXException ex) {
            Logger.getLogger(main_menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(main_menu.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(jComboBox1.getSelectedItem()==null)
       {
           ErrorMassage.setForeground(Color.red);
           ErrorMassage.setText("please Add subject to can select ^_^");
       }
       else
       {
        int i = JOptionPane.showConfirmDialog(this, "Are you sure to delete this Subject"+(String) jComboBox1.getSelectedItem()+" and his Questions?", "Delet Subject",2);
        if(i ==0 )/*ok*/
        {
            try {
                management.Delete((String) jComboBox1.getSelectedItem(), "data/Data.xml");
                ErrorMassage.setForeground(Color.decode("#264b14"));
                ErrorMassage.setText("Delete subject "+ (String) jComboBox1.getSelectedItem() +" is sucsses full ^_^");
                jComboBox1.removeItem((String) jComboBox1.getSelectedItem());
            } catch (ParserConfigurationException ex) {
                System.out.println("Error in function main menu button delet subject *~*");
            }
        }
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String s = jTextField1.getText();
            boolean flage = false;
            for(int i =0 ;i<s.length();i++)
            {
                if(s.charAt(i) != ' ')
                {
                    flage = true;
                    break;
                }
            }
        if(jTextField1.getText().equals("Enter Subject Name")||jTextField1.getText().equals("")||!flage)
        {
            ErrorMassage.setForeground(Color.red);
            ErrorMassage.setText("Please Enter Subject Name >_<");
            jTextField1.setText("");
        }
        else
        {
            if(management.add_subject(jTextField1.getText(), "data/Data.xml"))
            {
                ErrorMassage.setForeground(Color.decode("#264b14"));
                ErrorMassage.setText("Add subject "+jTextField1.getText()+" succesfull ^_^");
                jComboBox1.addItem(jTextField1.getText());
                jTextField1.setText("");
            }
            else
            {
                ErrorMassage.setForeground(Color.red);
                ErrorMassage.setText("subject "+jTextField1.getText()+"is exist ^_^");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(jComboBox1.getSelectedItem()==null)
       {
           ErrorMassage.setForeground(Color.red);
           ErrorMassage.setText("please Add subject to can select ^_^");
       }
       else
       {
        GnerateFrame gno = new GnerateFrame((String) jComboBox1.getSelectedItem());
        gno.setBounds(0, 0,1048, 660);
        this.setVisible(false);
        this.removeAll();
        this.add(gno);
        this.repaint();
        this.setVisible(true);
        gno.setVisible(true);
       }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrorMassage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
