/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import hci_project.ExamInfo;
import hci_project.Question;
import hci_project.management;
import java.awt.Font;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.TitledBorder;
import org.xml.sax.SAXException;

/**
 *
 * @author moroclash
 */
public class ShowQuestionForm extends javax.swing.JPanel {

    /**
     * Creates new form ShowQuestionForm
     */
    private String subjectname,model;
    private ExamInfo exam; 
    public  int n ;
    public ShowQuestionForm(String subject,ArrayList<Question> a,ExamInfo exam,int n ,String model) {
        try {
            this.subjectname = subject;
            this.exam=exam;
            this.n=n;
            this.model=model;
            initComponents();
            TitledBorder titel ;
            if(n==1)
               titel =new TitledBorder("All "+subjectname+" Questions");
            else 
                titel =new TitledBorder("Exam "+exam.getExamname()+" Model ("+model+") Questions");
            
            titel.setTitleFont(new Font("Tahoma", Font.BOLD, 28));
            this.setBorder(titel);
            
                
                int i=1;
                String txt = "" ;
                String Arr[];
                for(Question Q : a)
                {   
                    Arr = Q.getMSQ();
                    String an1=Q.getAnswers()[0],an2=Q.getAnswers()[1],an3=Q.getAnswers()[2];
                    for(int w=0;w<Arr.length;w++)
                    {
                        System.out.println("1111");
                        System.out.println(Arr[w]);
                        if(Arr[w] == null)
                        {
                            Arr[w]=" ";
                        }
                        else
                        {
                            if(Arr[w].equals(an1)||Arr[w].equals(an2)||Arr[w].equals(an3))
                            {
                                Arr[w]+="                     (true)";
                                System.out.println("yes");
                            }
                        }
                    }
                    
                   // a1=Arr[0];a2=Arr[1];a3=Arr[2];a4=Arr[3];a5=Arr[4];
                    /*if(a3 == null)
                        a3= " ";
                    if(a4 == null)
                        a4= " ";
                    if(a5 == null)
                        a5= " ";*/
                    String lvl = "";
                    if(Q.getQlevel()==1)
                        lvl = "Easy";
                    else if (Q.getQlevel()==2)
                        lvl = "Meduim";
                    else 
                        lvl = "Hard";
                    txt +=i+") "+Q.getQbody()+"                   "+lvl+"\n\n"+"A) "+Arr[0]+"\n"+"B) "+Arr[1]+"\n"+"C) "+Arr[2]+"\n"+"D) "+Arr[3]+"\n"+"E) "+Arr[4]+"\n\n\n";
                    i++;
                }
            jTextArea1.setText(txt);
        } catch (Exception ex) {
            System.out.println("Error in function showQustionForm *~*");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(198, 236, 183));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "All Supject Question", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Jomolhari", 1, 24))); // NOI18N
        setPreferredSize(new java.awt.Dimension(926, 600));

        jTextArea1.setBackground(new java.awt.Color(29, 17, 17));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(243, 250, 253));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButton1.setText("Backe");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(n==1)
        {
            try{
                ArrayList<ExamInfo> a = management.SubjectExams(subjectname);
                ArrayList<String> s = new ArrayList<>();
                for(ExamInfo x : a)
                {
                    s.add(x.getExamname());
                }
            Search_frame show = new Search_frame(subjectname,Integer.toString(management.QuestionsNumber(subjectname,"data/Data.xml")),  s);
            show.setBounds(0, 0,1048, 660);
            this.setVisible(false);
            this.removeAll();
            this.add(show);
            this.repaint();
            this.setVisible(true);
            show.setVisible(true);
            }catch(Exception ex){System.out.println("Error in function ShowQuestionForm in line 115 <_>");}     
        }
        else if(n==2)
        {
            ExameFrame exa = new ExameFrame(exam, subjectname);
            exa.setBounds(0, 0,1048, 660);
            this.setVisible(false);
            this.removeAll();
            this.add(exa);
            this.repaint();
            this.setVisible(true);
            exa.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
